models.py

Algo así me estoy imaginando. Para al momento de generar un board nuevo, podamos usar `random.sample` en este deck y estamos. Me gustaría ponerle protección a estos objetos para asegurar que no me los modifiquen algo estilo `Object.freeze` en JS, pero nada, veo eso luego.
Por el momento consideren `TILES_DECK` read-only please jeje.

Tile class

---

models.py

Basic models for board representation. 
Looks like this:

Basic Board Representation (no graph yet)

---

algorithms.py
models.py

Me estoy imaginando estos signatures para los métodos. Qué creen?

Player color enum and Algorithms signatures

---

Pipfile
catanatron/algorithms.py
catanatron/models.py
tests/test_model.py

This introduces an api like:
```
board = Board()
board.build_settlement(Color.RED, (0, 0, 0), NodeRef.SOUTH, initial_placement=True)
board.build_road(Color.RED, (0, 0, 0), EdgeRef.SOUTHEAST)
board.build_road(Color.RED, (0, 0, 0), EdgeRef.EAST)
board.build_settlement(Color.RED, (0, 0, 0), NodeRef.NORTHEAST)
```
where these methods "raise" if they are an invalid placement.
A side-effect of getting these methods working was the graph representation `self.graph` and the algorithms for finding connected components (will be helpful for longest road computation) and computing buildable edges/nodes.
PTAL, thanks!

Basic game logic

---

catanatron/models/board_algorithms.py
tests/test_board_algorithms.py

Instead of brute-force, now optimized by using DFS from every possible node.

Better longest road implementation

---

catanatron/game.py
catanatron/models/board.py
tests/test_game.py

Road possible actions

---

.github/workflows/python-app.yml
Pipfile
Pipfile.lock
README.md

Testing coveralls.io README.md badge.
PTAL, thanks!

Updated README.md

---

catanatron/game.py
catanatron/models/decks.py
catanatron/models/enums.py
tests/test_game.py
tests/test_resource_decks.py

Robber. Possible actions and moving/stealing logic

---

README.md
catanatron/game.py
catanatron/models/enums.py
catanatron/models/player.py
tests/test_game.py

Discard mechanism: tick_queue and Player.discard

---

catanatron/game.py
server.py
tests/test_game.py
ui/src/pages/Board.js
ui/src/pages/ControlPanel.js
ui/src/pages/GamePage.js
ui/src/pages/Node.js
ui/src/pages/Robber.js
ui/src/pages/SidePanel.js
ui/src/pages/Tile.js

Improvements

---

Pipfile
Pipfile.lock
README.md
database.py
docker-compose.yml
play.py
server.py

Play script and database persistance

---

catanatron/game.py
catanatron/models/actions.py
catanatron/models/player.py
tests/models/test_actions.py
tests/test_game.py

Took a stab at the "play year of plenty" action. Let me know if I missed anything. I think there are a few edge cases to consider still -- i.e. can't play more than one dev card in a single turn, and low amounts of cards in the bank thus not being able to get a combination of two cards -- but think the rest makes sense.

Play Year of Plenty

---

catanatron/game.py
catanatron/models/player.py
tests/models/test_player.py
tests/test_game.py

Allow only one dev card per turn

---

catanatron/game.py
catanatron/json.py
catanatron/models/actions.py
catanatron/models/board.py
catanatron/models/board_initializer.py
catanatron/models/map.py
catanatron/models/player.py
tests/models/test_actions.py
tests/models/test_board.py
tests/test_algorithms.py
tests/test_game.py
ui/src/pages/Board.js
ui/src/pages/Edge.js
ui/src/pages/Node.js
ui/src/pages/SidePanel.js

Many changes including:
- Moving more player state to Player (has_rolled, roads_available, etc...)
- Eliminating discarding possibilities
- Giving deterministic and ordered IDs to Tiles, Ports, etc...
- Simplifying UI to allow clicking nodes, edges, etc...
- Changing some actions for ease of serializability.

Towards ML Infra

---

.github/workflows/python-app.yml
catanatron/game.py
tests/integration_tests/test_replay.py

Remove replay_game functionality

---

catanatron_core/catanatron/game.py
catanatron_core/catanatron/state_functions.py
catanatron_experimental/catanatron_experimental/cli/accumulators.py
catanatron_experimental/catanatron_experimental/cli/cli_players.py
catanatron_experimental/catanatron_experimental/machine_learning/utils.py
catanatron_experimental/catanatron_experimental/notebooks/Overview.ipynb
catanatron_experimental/catanatron_experimental/play.py
catanatron_experimental/catanatron_experimental/utils.py
catanatron_server/catanatron_server/api.py
tests/test_game.py

Change action_callbacks for Accumulator interface
New Console Output

Accumulator and new console output

---

catanatron_core/catanatron/json.py
tests/test_json.py

Server was responding 500 on POST /actions.
PTAL, thanks!

Fix action_from_json bug

---

catanatron_core/catanatron/models/map.py
catanatron_core/catanatron/state_functions.py
catanatron_experimental/catanatron_experimental/play.py
catanatron_gym/catanatron_gym/envs/catanatron_env.py
catanatron_gym/catanatron_gym/features.py
tests/integration_tests/test_gym.py
tests/test_gym.py
tests/test_machine_learning.py

Gym Improvements

---

catanatron_gym/catanatron_gym/envs/catanatron_env.py
tests/test_gym.py
ui/src/pages/Node.js
ui/src/pages/ZoomableBoard.js

Gym improvements and UI debugging

---

catanatron_core/setup.py
catanatron_gym/setup.py

Going to have both packages have same version to know they come from the same commit.

Bump versions to 3.2.0

---

catanatron_experimental/catanatron_experimental/cli/cli_players.py
catanatron_experimental/catanatron_experimental/machine_learning/players/minimax.py
catanatron_experimental/catanatron_experimental/machine_learning/players/tree_search_utils.py

SameTurnAlpha and More Aggressive Prunning

---

.github/workflows/python-app.yml
catanatron_experimental/catanatron_experimental/cli/accumulators.py
catanatron_gym/README.md
catanatron_gym/catanatron_gym/__init__.py
catanatron_gym/catanatron_gym/envs/catanatron_env.py
catanatron_gym/setup.py
tests/test_gym.py

Gym is now deprecated, see https://github.com/openai/gym.

Use gymnasium instead of gym

---

tests/test_game.py

Test that stealing longest road works when building a road that surpasses the current longest road and not just matching it in length. A  similar approach can be used to test other strategies such as when a house is built in between an opponent's longest road and hence making their longest road smaller. Unfortunately setting up the test required setting up a lot of game state variables since we are skipping the initial phases of the game just to set up this example state, so am wondering if you envisioned a cleaner way.

test road steal work when applying BUILD_ROAD action

---

.github/workflows/perf-regression.yml
.github/workflows/python-app.yml
Dockerfile.web
README.md
all-requirements.txt
catanatron_core/catanatron/models/actions.py
catanatron_core/catanatron/models/coordinate_system.py
catanatron_core/catanatron/models/decks.py
catanatron_core/catanatron/models/map.py
catanatron_core/catanatron/state.py
catanatron_experimental/catanatron_experimental/benchmarks/benchmark_edge_id.py
catanatron_experimental/catanatron_experimental/machine_learning/players/mcts.py
catanatron_experimental/catanatron_experimental/machine_learning/players/playouts.py
catanatron_experimental/catanatron_experimental/rllibtest.py
catanatron_gym/catanatron_gym/board_tensor_features.py
catanatron_gym/catanatron_gym/features.py
catanatron_server/catanatron_server/api.py
catanatron_server/setup.py

Since `tensorflow` is not easily installable in many Apple silicon computers and potentially other environments, removing it from the required dependencies. Also in previous PRs we made it so that the project lazy-loads it, so that you can run simulations without having TF installed. Only if you require a feature that needs TF will the project fail with such an error message.

Update requirements.txt (to not depend on TF)

---

catanatron_core/catanatron/models/map.py
tests/models/test_map.py

Fixes https://github.com/bcollazo/catanatron/issues/263.

Fix adjacent-same-resource tile production bug

---

catanatron_experimental/catanatron_experimental/Overview.ipynb

Fixes #249: Fix Overview.ipynb

---

.github/workflows/build.yml
catanatron_env/pyproject.toml

Trying to support Python 3.11 as well (since this is the last one officially supported by Tensorflow).

Try supporting 3.11

---

tests/machine_learning/test_mcts.py

Testing in preparation for an AlphaZero attempt.

Add basic MCTS Test

---

README.md
catanatron/catanatron/cli/play.py
catanatron/catanatron/gym/accumulators.py
catanatron/catanatron/gym/utils.py
pyproject.toml
tests/integration_tests/test_play.py

Allows user to output data in Parquet format. Like so:

Parquet Output and --output-format

---

.github/workflows/build.yml
catanatron/catanatron/gym/README.md
catanatron/catanatron/gym/accumulators.py
catanatron/catanatron/gym/envs/catanatron_env.py
catanatron/catanatron/gym/utils.py
examples/gym_example.py
examples/gym_vectorized_example.py
examples/sb3_contrib_example.py
tests/test_gym.py

- Improving the offline generation of data (I believe the RETURN columns and DISCOUNTED_) where wrong.
- Improving Typing and adding more examples of how to use Gym (showing vectorized environment)

Improve RL Infrastructure

---

catanatron/catanatron/gym/utils.py
catanatron_experimental/catanatron_experimental/data_logger.py
catanatron_experimental/catanatron_experimental/mcts_score_collector.py
docs/BLOG_POST.md
tests/integration_tests/test_play.py

Supposedly .gzip is an invention of mine 😅 . It's not a standard extension.

Use correct .gz extension
