bcollazo/catanatron

- README.md
- catanatron/game.py
- catanatron/models/actions.py
- catanatron/models/player.py
- database.py
- play.py
- server.py
- tests/models/test_actions.py
- tests/test_game.py
- tests/test_json.py
- ui/public/index.html
For machine learning, we need to be able to iterate over all the states of a game. Saving the state and game object to the database on every tick proved to be too slow (increase avg finish time of a game from ~5 secs to ~1 min). So we instead make the refactors necessary to be able to have a function `replay_game` that given a game, can yield all the states of that game. In particular, we had to make the Initial Building Phase to go through the `game.execute(action)` mechanism like everything else.
As such, we created new `ActionType`s that tell the .execute function not to charge for initial roads for example.
Similarly, we change the Discard logic to be just another branching spot in the game logic, so that a tree-exploring algorithm can decide with the same API as the rest of the …
> Make initial build phase tick-able (and replay-able). Replay game functionality.

- README.md
- catanatron/algorithms.py
- catanatron/game.py
- catanatron/models/actions.py
- catanatron/models/board.py
- pytest.ini
- tests/models/test_actions.py
- tests/test_game.py
- ui/src/pages/GamePage.js
> Fix bugs and miscellaneous

- catanatron_core/catanatron/models/board.py
- catanatron_gym/catanatron_gym/features.py
Adds minor changes to simplify code.
- In board.py: Initialization for set can use `{}` directly.
- In board.py: Replace `get_edge_color` exception handling with `.get` dictionary method that handles key-value retrieval in similar way without resorting to exceptions.
- In features.py: Is it necessary to create a copy of each layer? I may be reading it incorrectly but it seems we only append to the set at each iteration of the for loop so there's no need for the `level_nodes = set(last_layer_nodes)` line? I may be missing something.
> Minor suggested changes

- catanatron_core/catanatron/__init__.py
- catanatron_core/catanatron/game.py
- catanatron_core/catanatron/json.py
- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/state.py
- catanatron_core/catanatron/state_functions.py
- catanatron_experimental/catanatron_experimental/benchmarks/benchmark_create_sample_vector.py
- catanatron_experimental/catanatron_experimental/benchmarks/benchmark_game_copy.py
- catanatron_experimental/catanatron_experimental/cli/accumulators.py
- catanatron_experimental/catanatron_experimental/data_logger.py
- catanatron_experimental/catanatron_experimental/machine_learning/players/minimax.py
- catanatron_gym/catanatron_gym/envs/catanatron_env.py
- catanatron_gym/catanatron_gym/features.py
- catanatron_server/catanatron_server/api.py
- tests/integration_tests/test_replay.py
- tests/models/test_actions.py
- tests/test_game.py
- tests/test_machine_learning.py
- tests/test_state.py
- tests/utils.py
Further separation of state with player decision making logic.
This should make easier to be able to serialize/de-serialize games without having to serialize the player classes. I am thinking just storing a JSON of that player-class-independent state, and some importlib-enabled references to the player classes per color would work? This way Python processes could import the players (if in path) and there would be no need to serialize player classes.
What about players that have internal state during the game(?). Lets not support them for now, if anyone wants local state and serialization, they would have to use a global state instead...
> Reduce dependency on state.players on favor of state.colors

- .github/workflows/python-app.yml
- catanatron_core/setup.py
- catanatron_gym/setup.py
It seems Gym 0.25 now uses "render_modes" instead of "render.modes" which was yielding this error: https://github.com/bcollazo/catanatron/discussions/55#discussioncomment-3163715.
Quick fix here is to add a CI check that ensures at least standalone `catanatron-gym` is installable and usable, and to lock the required gym to `gym==0.21.0`.
> Ensure PyPi versions work

- catanatron_core/catanatron/models/enums.py
- catanatron_gym/catanatron_gym/features.py
- docs/requirements.txt
This just updates a couple build dependencies and tries out the new "Build PRs" functionality from readthedocs.org.
It seems will be stuck with mistune==0.8.4 for now.
> Fix DOCS build

- Dockerfile.paperspace
- catanatron_core/catanatron/game.py
- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/models/board.py
- tests/test_accumulators.py
Implements 4 different optimizations:
- Disable accumulator copy
- Copying is quite expensive, the code currently copies on every step when there is an accumulator used. This defaults to not copying and adds functionality to override if wanted.
- Cache buildable subgraph
- The buildable subgraph doesn't change during the game since it only relies on the land tiles. We should just compute this once and re-use. To make this easy to change in the code I've implemented this cache as a lazy-compute.
- Cache buildable edges
- Buildable edges don't always change, they only change when building an edge. So we cache unless a build action is done.
- Cache port resources
Port resources only change when a settlement is built, this improvement caches the port resources and clears the cache when a …
> Speed up Catanatron performance by adding caches and removing unnecessary copy-ing

- catanatron_core/catanatron/state.py
- tests/test_game.py
I wasn't sure the discarding process would ensure everyone would discard (not only those to the "left" of the person rolling a 7). Wrote a test to be sure.
> Discarding Test

- catanatron_core/catanatron/state.py
- catanatron_core/catanatron/state_functions.py
To keep consistent with `player_freqdeck_add`.
> Rename to player_freqdeck_subtract

- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/state.py
- tests/test_game.py
Code was allowing to use ROAD_BUILDING card only if user had money for roads. Should allow to use even if no money for roads. It was also not cleaning correctly the `state.free_roads_available` state.
> Fix ROAD_BUILDING bugs

- catanatron_experimental/catanatron_experimental/play.py
See https://github.com/bcollazo/catanatron/issues/207. The idea is to avoid users accidentally using `-players=...`.
> Remove -p option from CLI

- catanatron_core/catanatron/game.py
- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/models/decks.py
- catanatron_core/catanatron/models/enums.py
- catanatron_core/catanatron/models/player.py
- catanatron_core/catanatron/state.py
- catanatron_core/catanatron/state_functions.py
- tests/test_game.py
This PR introduces 5 new "actions" that allow player-to-player trading mechanics to ensue.
- OFFER_TRADE
- ACCEPT_TRADE (to answer if asked)
- REJECT_TRADE (to answer if asked)
- CONFIRM_TRADE (so that players can select with whom to proceed if multiple players accepted offer)
- CANCEL_TRADE (so that players can "regret" offering trades)
Because the space of possible "trade offers" a player can make is infinite, we keep trading actions outside of the `playable_actions` that is generated on every turn. In particular, now "valid actions" are anything inside the `playable_actions` array _or_ an OFFER_TRADE action that is made at the right time by the right player with right resources.
To implement the "control sequence" that the `Game` class must carry out when a trade is offered (a …
> Implement Domestic Trading Mechanics

- ui/src/pages/Board.scss
- ui/src/pages/Tile.js
- ui/src/pages/Tile.scss
Adds pips to the relevant tiles using the '•' character, and a helper to map from the Number on the tile to the number of pips.
Opening this for review but haven't really tested it locally yet.
> Fixes #160: Add pips to tiles

- catanatron_core/catanatron/models/board.py
- catanatron_gym/catanatron_gym/board_tensor_features.py
- catanatron_gym/catanatron_gym/features.py
The `global` keyword should be used when the variable in question is being assigned to as otherwise it would create a local variable as opposed to operating on the global variable.
I.e.
```
global STATIC_GRAPH
STATIC_GRAPH = new_graph()
```
This PR removes uses of `global` in cases where the variable is only being accessed and not assigned to.
> Remove unnecessary 'global' keyword uses

- catanatron_core/catanatron/game.py
- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/models/board.py
- catanatron_core/catanatron/models/enums.py
- catanatron_core/catanatron/models/map.py
- catanatron_core/catanatron/state.py
- catanatron_core/catanatron/state_functions.py
- catanatron_core/setup.py
Initial PR to prepare the codebase to use mypy. This PR just addresses the issues found by running:
```
$ mypy catanatron_core
```
With this PR, the output is:
```
$ mypy catanatron_core
catanatron_core/catanatron/models/board.py:58: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
catanatron_core/catanatron/models/board.py:62: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
catanatron_core/catanatron/models/board.py:66: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
catanatron_core/catanatron/models/board.py:71: note: By default the bodies of untyped …
```
> Fix Mypy issues in catanatron_core

- .github/workflows/perf-regression.yml
- catanatron_experimental/catanatron_experimental/machine_learning/players/minimax.py
- tests/integration_tests/test_speed.py
Added to the integration tests a few benchmarks consisting  of 100 ticks of games of 3 Random Players vs WeightedRandomPlayer, AlphaBetaPlayer, and SameTurnAlphaBetaPlayer. Also one of just 4 SimplePlayers.
These benchmarks are run with the new workflow and compare the results with the master branch. Should be helpful too quickly show if a PR is introducing a regression in terms of performance.
Not 100% convinced the workflow works as intended, but at least it dumps enough useful info to manually see if the PR is introducing a regression. The benefits here are to introduce a consistent and easy way to test performance and catch regressions for both the game logic and specialized player logic.
Also found a bug in AlphaBeta where it would sometimes return None as an action. Might be worth …
> workflow and performance tests for github actions

- catanatron_core/catanatron/game.py
This is probably why seed wasn't being honored, since `0 or random` will be random everytime, its better to check explicitly for None.
> honor seed=0 by checking if seed is none instead of using or operator

- catanatron_core/catanatron/state_functions.py
- catanatron_experimental/catanatron_experimental/machine_learning/players/tree_search_utils.py
Hi!
Changes in this PR:
- `execute_spectrum` now uses the correct knowable dev card probabilities rather than the base ones. It could get smarter and use the (unknowable) bank probabilities instead, but I didn't want to leak any info accidentally. I expect this to have a very small impact but I think is still worth merging
- `execute_spectrum` now uses the correct robber steal probabilities - based on the fact that the bot should be able to track other players hands (and therefore there's no leakage of information here). 
- Style changes. Please feel free to revert these! Just made DETERMINISTIC_ACTIONS look like a constant and added a small helper function.
- Filter actions to playable_actions before execute_spectrum and therefore remove some try blocks. This is definitely a change you …
> Fix dev card hallucination bug and other expand_spectrum changes

- catanatron_core/catanatron/models/actions.py
- catanatron_core/catanatron/models/map.py
- catanatron_core/catanatron/models/player.py
- catanatron_core/catanatron/players/weighted_random.py
- catanatron_core/catanatron/state.py
- catanatron_core/catanatron/state_functions.py
Implements a collection of minor style improvements:
- Prefer `random.choice` to select a random element of a list.
- Use `@dataclass` on LandTile and Port classes.
- Iterate over .values() instead of .items() if only iterating over values.
- Return early if exit conditions are met in `maintain_longest_road` and `maintain_largest_army`.
No logic changes in this PR, just code style changes mainly. I think they can help make the code easier to change later.
> Collection of minor improvements

- .gitignore
- docker-compose.yml
* add volume to database container in `docker-compose`
* add `db-data` folder to gitignore
> add volume to database container for persisting data

- catanatron_rust/src/enums.rs
- catanatron_rust/src/game.rs
- catanatron_rust/src/main.rs
- catanatron_rust/src/map_instance.rs
- catanatron_rust/src/state.rs
- catanatron_rust/src/state/move_application.rs
- catanatron_rust/src/state/move_generation.rs
- catanatron_rust/src/state_vector.rs
This is still a work in progress, I'm learning Rust as I go. I'll try and push to this branch as I make progress on the TODOs.
> Rust Rewrite

- catanatron/catanatron/json.py
- catanatron/catanatron/state_functions.py
- catanatron/catanatron/web/api.py
- catanatron/catanatron/web/models.py
- ui/src/App.tsx
- ui/src/components/AnalysisBox.scss
- ui/src/components/AnalysisBox.tsx
- ui/src/components/NumericTextInput.scss
- ui/src/components/NumericTextInput.tsx
- ui/src/components/ReplayBox.scss
- ui/src/components/ReplayBox.tsx
- ui/src/components/RightDrawer.scss
- ui/src/components/RightDrawer.tsx
- ui/src/pages/GameScreen.tsx
- ui/src/pages/ReplayScreen.scss
- ui/src/pages/ReplayScreen.tsx
- ui/src/utils/api.types.ts
- ui/src/utils/apiClient.ts
- ui/src/utils/events.ts
Frontend changes:
- Closed #54, replay feature now implemented, it looks like this
- refactored some components: AnalysisBox, ReplayBox, RightDrawer
- new route: /replays/:gameId
Backend changes:
- route /games/<string:game_id>/states/<string:state_index> also returns the state_index along with game state (could be cleaner to put state_index inside of the game object we're returning)
> FEATURE: add game replay
